// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface GetTicker {
  data:     Data;
  metadata: Metadata;
}

export interface Data {
  id:                 number;
  name:               string;
  symbol:             string;
  website_slug:       string;
  rank:               number;
  circulating_supply: number;
  total_supply:       number;
  max_supply:         null;
  quotes:             { [key: string]: Quote };
  last_updated:       number;
}

export interface Quote {
  price:              number;
  volume_24h:         number;
  market_cap:         number;
  percent_change_1h:  number;
  percent_change_24h: number;
  percent_change_7d:  number;
}

export interface Metadata {
  timestamp: number;
  error:     null;
}
